import argparse
import json
from pathlib import Path


def _load_jsonl(path: Path) -> list[dict]:
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")


def main() -> None:
    p = argparse.ArgumentParser(
        description="Build finetuning/sft_12hz.py compatible train_raw.jsonl from dist teacher artifacts."
    )
    p.add_argument(
        "--teacher-metadata-jsonl",
        default="dist/teacher_artifacts/metadata.jsonl",
        help="metadata.jsonl generated by dist/10_build_teacher_codes.py",
    )
    p.add_argument("--ref-audio", default="dist/ref_audio.WAV")
    p.add_argument("--output-jsonl", default="dist/train_raw.jsonl")
    args = p.parse_args()

    meta_rows = _load_jsonl(Path(args.teacher_metadata_jsonl))
    ref_audio = str(Path(args.ref_audio))

    out_rows: list[dict] = []
    for i, r in enumerate(meta_rows):
        wav_path = r.get("wav_path")
        text = r.get("text")
        if not wav_path or not text:
            continue
        out_rows.append(
            {
                "id": r.get("id", f"{i:06d}"),
                "audio": wav_path,
                "text": text,
                "ref_audio": ref_audio,
                "language": r.get("language", "Auto"),
            }
        )

    _write_jsonl(Path(args.output_jsonl), out_rows)
    print(f"[OK] wrote {len(out_rows)} rows -> {args.output_jsonl}")


if __name__ == "__main__":
    main()

